# Generated by Django 5.1.4 on 2024-12-12 22:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reflectionresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='eveningreflection',
            old_name='highlights_of_the_day',
            new_name='Highlights_of_the_day',
        ),
        migrations.RenameField(
            model_name='eveningreflection',
            old_name='what_i_learned_today',
            new_name='What_did_I_learn_today',
        ),
        migrations.RenameField(
            model_name='morningreflection',
            old_name='daily_affirmation',
            new_name='Daily_affirmation',
        ),
        migrations.RenameField(
            model_name='morningreflection',
            old_name='grateful_for',
            new_name='Three_things_I_am_grateful_for',
        ),
        migrations.RenameField(
            model_name='morningreflection',
            old_name='what_would_make_today_great',
            new_name='What_would_make_today_great',
        ),
        migrations.RemoveField(
            model_name='bestcasescenario',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='eveningreflection',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='morningreflection',
            name='journal_entry',
        ),
        migrations.AddField(
            model_name='bestcasescenario',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bestcasescenario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eveningreflection',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='eveningreflection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morningreflection',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='morningreflection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
