# Generated by Django 5.1.4 on 2024-12-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_morningreflection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveningreflection',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='morning_reflections/'),
        ),
    ]
