# Generated by Django 5.1.4 on 2024-12-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_eveningreflection_mood_morningreflection_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningreflection',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/morning_reflections/'),
        ),
        migrations.AlterField(
            model_name='morningreflection',
            name='Mood',
            field=models.CharField(blank=True, choices=[('bad', 'Bad'), ('not_great', 'Not Great'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great')], default='okay', max_length=10, null=True),
        ),
    ]
