# Generated by Django 5.1.4 on 2024-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_image_morningreflection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveningreflection',
            name='Mood',
            field=models.CharField(choices=[('bad', 'Bad'), ('not_great', 'Not Great'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great')], default='okay', max_length=10, null=True),
        ),
    ]
