# Generated by Django 5.1.4 on 2024-12-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_highlights_of_the_day_eveningreflection_highlights_of_the_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestcasescenario',
            old_name='best_case_scenario',
            new_name='Best_case_scenario',
        ),
        migrations.AddField(
            model_name='bestcasescenario',
            name='Scenario_Topic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
