# Generated by Django 5.1.4 on 2024-12-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_eveningreflection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveningreflection',
            name='Mood',
            field=models.CharField(choices=[('bad', 'Bad'), ('not_great', 'Not Great'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great')], default='okay', max_length=10),
        ),
        migrations.AddField(
            model_name='morningreflection',
            name='Mood',
            field=models.CharField(choices=[('bad', 'Bad'), ('not_great', 'Not Great'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great')], default='okay', max_length=10),
        ),
    ]
