# Generated by Django 5.1.4 on 2024-12-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_morningreflection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morningreflection',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='morning_reflections/'),
        ),
    ]
