# Generated by Django 5.1.4 on 2024-12-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_morningreflection_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morningreflection',
            old_name='Image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='morningreflection',
            name='Mood',
            field=models.CharField(choices=[('bad', 'Bad'), ('not_great', 'Not Great'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great')], default='okay', max_length=10, null=True),
        ),
    ]
