# Generated by Django 5.1.4 on 2024-12-16 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_eveningreflection_mood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveningreflection',
            name='Mood',
            field=models.CharField(choices=[('bad', 'Bad'), ('not_great', 'Not Great'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great')], default='okay', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='morningreflection',
            name='Mood',
            field=models.CharField(choices=[('bad', 'Bad'), ('not_great', 'Not Great'), ('okay', 'Okay'), ('good', 'Good'), ('great', 'Great')], default='okay', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad', models.IntegerField(default=0)),
                ('not_great', models.IntegerField(default=0)),
                ('okay', models.IntegerField(default=0)),
                ('good', models.IntegerField(default=0)),
                ('great', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
